spring:
  profiles:
    active:  
       - dev
---
spring:
  profiles: dev
  application:
   name: microservicecloud-config-aaron-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-aaron-test
